version: '3'

# create network so that another container can access it
networks:
  gps-api-network:
    name: gps-api
    driver: bridge

services:
  postgres:
    container_name: gps-api-postgres-db-container
    image: postgres:latest
    environment:
      POSTGRES_DB: gpsdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - gps-api-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


